# Generated by Django 6.0.7 on 2026-07-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discord_webhook_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
