# Generated by Django 6.0.7 on 2026-08-12 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_discord_id'),
        ('products', '0003_product_discord_webhook_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('target_date', models.DateField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='upcoming', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='products.product')),
            ],
            options={
                'ordering': ['order', 'target_date'],
                'abstract': False,
            },
        ),
    ]
