# Generated by Django 6.0.7 on 2026-10-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_productmilestone"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
