# Generated by Django 6.0.7 on 2026-10-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_membership_is_leave_approver"),
        ("products", "0005_apikey_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="key",
            field=models.CharField(blank=True, default="", max_length=6),
        ),
        migrations.AddField(
            model_name="product",
            name="ticket_counter",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("key", ""), _negated=True),
                fields=("company", "key"),
                name="product_key_unique_per_company",
            ),
        ),
    ]
