# Generated by Django 6.0.7 on 2026-08-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(blank=True, default='', help_text='Discord user snowflake ID, used to mention the user in webhook notifications.', max_length=64),
        ),
    ]
