# Generated by Django 6.0.7 on 2026-09-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_externalaccesstoken_externalauthcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_leave_approver',
            field=models.BooleanField(default=False, help_text="Can approve or reject any employee's leave in this company."),
        ),
    ]
