# Generated by Django 6.0.7 on 2026-08-12 09:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_discord_id'),
        ('tickets', '0003_backfill_assignees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DSREntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('task_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ticket', 'Ticket Completion'), ('bug_fix', 'Bug Fix'), ('feature', 'Feature Development'), ('code_review', 'Code Review'), ('meeting', 'Meeting / Sync'), ('documentation', 'Documentation'), ('other', 'Other')], default='ticket', max_length=32)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('hours_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('blocked', 'Blocked')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_auto_logged', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsr_entries', to='accounts.company')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsr_entries', to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsr_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DSR Entry',
                'verbose_name_plural': 'DSR Entries',
                'ordering': ['-date', '-completed_time', '-created_at'],
            },
        ),
    ]
