# Generated by Django 6.0.7 on 2026-10-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsrentry',
            name='hours_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
