# Generated by Django 6.0.7 on 2026-10-04 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsr", "0002_alter_dsrentry_hours_spent"),
        ("products", "0006_ticket_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsrentry",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dsr_entries",
                to="products.product",
            ),
        ),
    ]
