# Generated by Django 6.0.7 on 2026-10-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0004_backfill_entry_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsrentry',
            name='source',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='dsrentry',
            name='source_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
