# Generated by Django 6.0.7 on 2026-10-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsr', '0005_dsr_entry_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsrentry',
            name='category',
            field=models.CharField(choices=[('ticket', 'Ticket Completion'), ('bug_fix', 'Bug Fix'), ('feature', 'Feature Development'), ('code_review', 'Code Review'), ('meeting', 'Meeting / Sync'), ('documentation', 'Documentation'), ('administration', 'Administration'), ('other', 'Other')], default='ticket', max_length=32),
        ),
    ]
