# Generated by Django 6.0.7 on 2026-07-26 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('error_captured', 'Error Captured'), ('error_resolved', 'Error Resolved'), ('ticket_created', 'Ticket Created'), ('ticket_resolved', 'Ticket Resolved'), ('feedback_received', 'Feedback Received'), ('survey_response', 'Survey Response'), ('member_joined', 'Member Joined'), ('member_removed', 'Member Removed'), ('product_created', 'Product Created'), ('auto_ticket', 'Auto Ticket Created')], max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('target_content_type', models.CharField(blank=True, default='', max_length=100)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
