# Generated by Django 6.0.7 on 2026-09-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('error_captured', 'Error Captured'), ('error_created', 'Error Created'), ('error_resolved', 'Error Resolved'), ('error_ignored', 'Error Ignored'), ('error_status_changed', 'Error Status Changed'), ('error_deleted', 'Error Deleted'), ('ticket_created', 'Ticket Created'), ('ticket_status_changed', 'Ticket Status Changed'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_commented', 'Ticket Commented'), ('ticket_resolved', 'Ticket Resolved'), ('ticket_deleted', 'Ticket Deleted'), ('feedback_received', 'Feedback Received'), ('survey_response', 'Survey Response'), ('survey_created', 'Survey Created'), ('survey_toggled', 'Survey Status Changed'), ('survey_deleted', 'Survey Deleted'), ('member_joined', 'Member Joined'), ('member_removed', 'Member Removed'), ('member_role_changed', 'Member Role Changed'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated'), ('product_deleted', 'Product Deleted'), ('api_key_created', 'API Key Created'), ('api_key_revoked', 'API Key Revoked'), ('version_added', 'Version Added'), ('version_removed', 'Version Removed'), ('access_granted', 'Access Granted'), ('access_revoked', 'Access Revoked'), ('rule_created', 'Rule Created'), ('rule_updated', 'Rule Updated'), ('rule_deleted', 'Rule Deleted'), ('rule_toggled', 'Rule Toggled'), ('auto_ticket', 'Auto Ticket Created'), ('attendance_checked_in', 'Attendance Checked In'), ('attendance_checked_out', 'Attendance Checked Out'), ('attendance_edited', 'Attendance Edited')], max_length=30),
        ),
    ]
