# Generated by Django 6.0.7 on 2026-07-26 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ingestion', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorgroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_groups', to='products.product'),
        ),
        migrations.AddField(
            model_name='erroroccurrence',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='erroroccurrence',
            name='error_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='ingestion.errorgroup'),
        ),
        migrations.AddField(
            model_name='erroroccurrence',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productversion'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='products.product'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productversion'),
        ),
        migrations.AddField(
            model_name='ingestedticket',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='ingestedticket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingested_tickets', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='errorgroup',
            unique_together={('product', 'fingerprint')},
        ),
    ]
