# Generated by Django 6.0.7 on 2026-10-04 08:11

import django.db.models.deletion
from django.db import migrations, models


def backfill_first_version(apps, schema_editor):
    """Give existing groups the release of their earliest occurrence that has one."""
    ErrorGroup = apps.get_model("ingestion", "ErrorGroup")
    ErrorOccurrence = apps.get_model("ingestion", "ErrorOccurrence")
    for group in ErrorGroup.objects.filter(first_version__isnull=True).iterator():
        first = (
            ErrorOccurrence.objects.filter(error_group=group, version__isnull=False)
            .order_by("created_at", "pk")
            .first()
        )
        if first:
            ErrorGroup.objects.filter(pk=group.pk).update(first_version_id=first.version_id)


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0002_initial"),
        ("products", "0004_productmilestone"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorgroup",
            name="first_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="products.productversion",
            ),
        ),
        migrations.AddField(
            model_name="errorgroup",
            name="regressed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="errorgroup",
            name="regression_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_first_version, migrations.RunPython.noop),
    ]
