# Generated by Django 6.0.7 on 2026-08-05 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Optional due date. Overdue tickets are highlighted.', null=True),
        ),
    ]
