# Generated by Django 6.0.7 on 2026-08-12 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productmilestone'),
        ('tickets', '0003_backfill_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='products.productmilestone'),
        ),
    ]
