# Generated by Django 6.0.7 on 2026-10-04 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_membership_is_leave_approver"),
        ("ingestion", "0003_error_trends"),
        ("products", "0006_ticket_keys"),
        ("tickets", "0005_ticketcomment_mentions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="number",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number__isnull", False)),
                fields=("product", "number"),
                name="ticket_number_unique_per_product",
            ),
        ),
    ]
