# Generated by Django 6.0.7 on 2026-10-06 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_backfill_ticket_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
