# Generated by Django 6.0.7 on 2026-07-26 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ingestion', '0002_initial'),
        ('products', '0001_initial'),
        ('tickets', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTicketRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(choices=[('error_threshold', 'Error Occurrence Threshold'), ('new_error', 'New Error Group')], default='error_threshold', max_length=30)),
                ('severity', models.CharField(blank=True, choices=[('', 'Any'), ('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='', max_length=20)),
                ('threshold_count', models.PositiveIntegerField(default=10, help_text='Number of occurrences to trigger within the time window.')),
                ('window_minutes', models.PositiveIntegerField(default=60, help_text='Time window in minutes.')),
                ('action', models.CharField(choices=[('create_ticket', 'Create Ticket'), ('notify_only', 'Notify Only')], default='create_ticket', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_assigned_rules', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_ticket_rules', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutoTicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('action_taken', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company')),
                ('error_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.errorgroup')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticket')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.autoticketrule')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
