# Generated by Django 6.0.7 on 2026-09-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Optional icon name from apps.core.icons.ICONS, e.g. coffee.', max_length=40),
        ),
    ]
