# Generated by Django 6.0.7 on 2026-10-01 12:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def backfill_split(apps, schema_editor):
    """Give every existing request the split its policy implied at the time.

    Without this the split would stay NULL, and the model's fallback reads the
    policy *as it is now* -- so unticking "paid" on Casual next month would
    retroactively turn everyone's already-approved March leave unpaid, and both
    the balance and any payroll run not yet issued would follow the new policy
    backwards. Freezing the split at migration time is what makes the same
    request mean the same thing for the rest of its life.
    """
    LeaveRequest = apps.get_model("leave", "LeaveRequest")
    for request in LeaveRequest.objects.select_related("policy").iterator():
        if request.policy.is_paid:
            request.paid_days = request.days
            request.unpaid_days = Decimal("0.0")
        else:
            request.paid_days = Decimal("0.0")
            request.unpaid_days = request.days
        request.save(update_fields=["paid_days", "unpaid_days"])


def clear_split(apps, schema_editor):
    """Reverse: forget the split, returning every row to the pre-split null."""
    LeaveRequest = apps.get_model("leave", "LeaveRequest")
    LeaveRequest.objects.update(paid_days=None, unpaid_days=None)


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leavepolicy_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='paid_days',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Days paid. Null on rows predating the split; see split.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='split_mode',
            field=models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='auto', help_text="Automatic, or an approver's manual override.", max_length=10),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='unpaid_days',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Days charged as unpaid. Null on rows predating the split.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='leavepolicy',
            name='max_consecutive_days',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Paid days in a single spell. Blank means unlimited. Days beyond this are charged as unpaid leave, not refused.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))]),
        ),
        migrations.AlterField(
            model_name='leavepolicy',
            name='max_days_per_year',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Paid leave days allowed per calendar year. Blank means unlimited. Days beyond this are charged as unpaid leave, not refused.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.RunPython(backfill_split, clear_split),
    ]
