# Generated by Django 6.0.7 on 2026-09-30 12:18

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_membership_is_leave_approver'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time(10, 0))),
                ('end_time', models.TimeField(default=datetime.time(19, 0))),
                ('break_minutes', models.PositiveIntegerField(default=60, help_text='Unpaid scheduled break, deducted from hours worked.')),
                ('grace_minutes', models.PositiveIntegerField(default=15, help_text='Arriving within this of start_time is on time.')),
                ('minor_band_end_minutes', models.PositiveIntegerField(default=30, help_text='Up to this late: minor_penalty.')),
                ('major_band_end_minutes', models.PositiveIntegerField(default=60, help_text='Up to this late: major_penalty. Beyond it, a half day.')),
                ('minor_penalty', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=8)),
                ('major_penalty', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=8)),
                ('penalty_currency', models.CharField(default='INR', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Work Shift',
                'verbose_name_plural': 'Work Shifts',
                'abstract': False,
            },
        ),
    ]
