# Generated by Django 6.0.7 on 2026-09-30 07:15

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_membership_is_leave_approver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('is_on_payroll', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Profile',
                'verbose_name_plural': 'Payroll Profiles',
                'ordering': ['user__username', '-effective_from'],
                'abstract': False,
                'unique_together': {('company', 'user', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(db_index=True)),
                ('working_days', models.PositiveIntegerField(default=0, help_text='Working days in the cycle, after weekends and holidays.')),
                ('is_locked', models.BooleanField(default=False, help_text='A locked run cannot be recalculated.')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'verbose_name_plural': 'Payroll Runs',
                'ordering': ['-period_start'],
                'abstract': False,
                'unique_together': {('company', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['-date'],
                'abstract': False,
                'unique_together': {('company', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('working_days', models.PositiveIntegerField(default=0)),
                ('paid_leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('unpaid_leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payable_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.company')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='payroll.payrollprofile')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'ordering': ['user__username'],
                'abstract': False,
                'unique_together': {('run', 'user')},
            },
        ),
    ]
