# Generated by Django 6.0.7 on 2026-09-30 08:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollprofile',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross monthly salary, before any unpaid leave deduction.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='payrollprofile',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Used only when there is no monthly salary.', max_digits=10),
        ),
    ]
