# Generated by Django 6.0.7 on 2026-09-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollprofile_monthly_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='late_half_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Days lost to arriving more than an hour after shift start.', max_digits=6),
        ),
        migrations.AddField(
            model_name='payslip',
            name='late_penalty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cash penalty for late arrivals inside the grace bands.', max_digits=10),
        ),
    ]
